service: windclock
provider:
  name: aws
  runtime: nodejs4.3

# you can overwrite defaults here
#  stage: dev
  region: eu-central-1

functions:
  update:
    handler: handler.update
    events:
      - schedule: rate(15 minutes)
